### ISSUE TITLE
Add a Ruby Sass compilation test

### ISSUE THREAD

**Issue by kaelig** [kaelig/sass-library-boilerplate#4]
Sometimes Libsass/node-sass compiles a mixin just fine but not Ruby Sass, although this is less and less common.

@xzyfer what are your thoughts on that? In the past it's been useful because Libsass was in a very unstable state so [I did use to test compilation in both environments](https://github.com/sass-mq/sass-mq/blob/master/scripts/test.sh) but is it still useful?

**Comment by xzyfer** [comment]
IMHO this is largely a problem of the past with regards to 3.4. It'll
possible to get yourself into trouble with 3.5 and 4.0 around the corner.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
